name: Trivy License Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy license scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: alpine/openssl
          scan-type: image
          scanners: license
          exit-code: '1'
